name: profile_ui
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  animated_segmented_tab_control: ^1.0.1
  awesome_dialog: ^3.0.2
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  equatable: ^2.0.5
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_dotenv: ^5.0.2
  flutter_markdown: ^0.6.12
  flutter_svg: ^1.1.5
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  http: ^0.13.5
  injectable: ^1.5.3
  json_annotation: ^4.7.0
  json_serializable: ^6.4.0
  path_provider: ^2.0.11
  simple_animations: ^4.2.0
  url_launcher: ^6.1.5

dev_dependencies:
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    # - assets/
